name: "Setup ROMs"
description: "This action downloads the ROMs required for the unittests of the Gymboy project."
runs:
  using: "composite"
  steps:
    - name: Download & Unzip ROMs (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        wget --no-check-certificate "${{ env.ROM_DOWNLOAD_URL }}" -O roms.zip
        unzip roms.zip
        rm roms.zip
      shell: bash
    - name: Move ROMs to directories (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        mv roms gymboy/resources
      shell: bash
    
    - name: Download & Unzip ROMs (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "${{ env.ROM_DOWNLOAD_URL }}" -OutFile "roms.zip"
        Expand-Archive -Path "roms.zip" -DestinationPath "."
        Remove-Item -Path "roms.zip"
      shell: pwsh
    - name: Move ROMs to directories (Windows)
      if: runner.os == 'Windows'
      run: |
        Move-Item -Force -Path "roms" -Destination "gymboy/resources"
      shell: pwsh
