name: "Setup ROMs"
description: "This action downloads the ROMs required for the unittests of the Gymboy project."
runs:
  using: "composite"
  steps:
    - name: Download & Unzip ROMs (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1pcr0nTKKyPyabXCx_oCl50t7mmSIgrFP" -O resources.zip
        unzip resources.zip
        rm resources.zip
      shell: bash

    - name: Download & Unzip ROMs (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest -Uri "https://docs.google.com/uc?export=download&id=1pcr0nTKKyPyabXCx_oCl50t7mmSIgrFP" -OutFile "resources.zip"
        Expand-Archive -Path "resources.zip" -DestinationPath "."
        Remove-Item -Path "resources.zip"
      shell: pwsh
