name: "Setup ROMs"
description: "This action downloads the ROMs required for the unittests of the Gymboy project."
runs:
  using: "composite"
  steps:
    - name: Download & Unzip ROMs
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1-6PIgpuhxmVNYW_KqVjyem8SDDDqhfgL" -O roms.zip
        unzip roms.zip
        rm roms.zip
      shell: bash
    - name: Make directories
      run: |
        mkdir -p gymboy/resources/roms/kirby/dream_land_1
        mkdir -p gymboy/resources/roms/mario/land_1
        mkdir -p gymboy/resources/roms/pokemon/gen_1
        mkdir -p gymboy/resources/roms/pokemon/gen_2
        mkdir -p gymboy/resources/roms/tetris/tetris
      shell: bash
    - name: Move ROMs to directories
      run: |
        mv kirby_dream_land_1.gb gymboy/resources/roms/kirby/dream_land_1
        mv super_mario_land_1.gb gymboy/resources/roms/mario/land_1
        mv pokemon_blue.gb gymboy/resources/roms/pokemon/gen_1
        mv pokemon_red.gb gymboy/resources/roms/pokemon/gen_1
        mv pokemon_yellow.gbc gymboy/resources/roms/pokemon/gen_1
        mv pokemon_gold.gbc gymboy/resources/roms/pokemon/gen_2
        mv pokemon_silver.gbc gymboy/resources/roms/pokemon/gen_2
        mv tetris.gb gymboy/resources/roms/tetris/tetris
      shell: bash
