name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: Publish TestPyPI (${{ matrix.os }}, Python ${{ matrix.python-version }})
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Update version for TestPyPI
        run: |
          VERSION_SUFFIX=$(date +%Y%m%d%H%M%S)
          sed -i "s/^version = \"\(.*\)\"/version = \"\1.dev$VERSION_SUFFIX\"/" pyproject.toml
      - name: Build package
        run: |
          uv build
      - name: Publish to TestPyPI
        run: |
          uv publish --index testpypi --token ${{ secrets.TEST_PYPI_API_TOKEN }}
