name: Run Unittests (Ubuntu)

on:
    workflow_run:
        workflows: ["Download ROMs (Ubuntu)"]
        types:
            - completed

jobs:
  run-unittests-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.10, 3.11, 3.12 ]

    name: ${{ matrix.os }} python-${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Run Unittests
        run: |
          python -m unittest