name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    steps:
      - name: Set up the repository
        uses: actions/checkout@v4

      - name: Set up ROMs
        uses: ./.github/actions/download-and-setup-roms

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Unittests with Coverage
        run: |
          uv run pytest --cov=gymboy --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
